### ISSUE TITLE
[5.7] route() returns wrong host with dev server

### ISSUE THREAD

**Issue by maglor** [laravel/lumen-framework#814] opened 2018-09-27 15:34 UTC
- Lumen Version: 5.7.1
- PHP Version: 7.1
- Database Driver & Version: PostgreSQL 10.4

### Description:

`route($name)` returns wrong host name with  PHP development server local server: `http://:/path`

### Steps To Reproduce:

1. run  PHP development server `php artisan serve` (http://127.0.0.1:8000)
2.  add to route.php
```
    $router->group(['prefix' => '/properties'], function() use ($router) {
        $router->get('', [
            'uses' => 'PropertiesController@index',
            'as'   => 'properties_index',
        ]);
    });
```
3.   `route( 'properties_index');` returns `http://:/properties`

**Comment by driesvints** [comment] 2018-10-02 13:14
Closing this as a duplicate of #513.

**Closed by driesvints** 2018-10-02 13:14 UTC
