### ISSUE TITLE
 Call to undefined method Application::resourcePath()

### ISSUE THREAD

**Issue by martinssipenko** [laravel/lumen-framework#494] opened 2016-10-03 15:23 UTC
`Illuminate/Support/ServiceProvider` uses `resourcePath` method from app instance, but the method is not present in `Laravel\Lumen\Application`, which leads to Fatal error.

This error can't be observed normally, because when installing Lumen, Illuminate packages with version `5.3.4` are being installed (current latest tagged). This bug appears in later versions of Illuminate, which have to been released, although framework has been. This can be reproduced by adding `"laravel/framework": "5.3.15"` to your Lumen project dependencies.

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Support/ServiceProvider.php#L71

**Comment by olimorris** [comment] 2016-10-05 21:29
I've just started getting the same error. Mine crops up when I run my tests. Previously it worked fine, then I performed a Composer Update and it's stopped working.

```
11) VerificationTest::a_trial_can_be_rejected_if_expired
Error: Call to undefined method Laravel\Lumen\Application::resourcePath()

/Users/Oli/Code/OliMorris-API/vendor/illuminate/support/ServiceProvider.php:71
/Users/Oli/Code/OliMorris-API/vendor/illuminate/pagination/PaginationServiceProvider.php:16
/Users/Oli/Code/OliMorris-API/vendor/illuminate/container/Container.php:508
/Users/Oli/Code/OliMorris-API/vendor/laravel/lumen-framework/src/Application.php:177
/Users/Oli/Code/OliMorris-API/vendor/laravel/lumen-framework/src/Application.php:563
/Users/Oli/Code/OliMorris-API/vendor/laravel/lumen-framework/src/Application.php:315
/Users/Oli/Code/OliMorris-API/vendor/illuminate/container/Container.php:746
/Users/Oli/Code/OliMorris-API/vendor/illuminate/container/Container.php:644
/Users/Oli/Code/OliMorris-API/vendor/laravel/lumen-framework/src/Application.php:211
/Users/Oli/Code/OliMorris-API/vendor/laravel/lumen-framework/src/Testing/DatabaseTransactions.php:14
/Users/Oli/Code/OliMorris-API/vendor/laravel/lumen-framework/src/Testing/TestCase.php:83
/Users/Oli/Code/OliMorris-API/vendor/laravel/lumen-framework/src/Testing/TestCase.php:70
```

**Comment by GrahamCampbell** [comment] 2016-10-05 22:26
A fix was merged a few days ago.

**Closed** 2016-10-05 22:26 UTC

**Comment by jeroenherczeg** [comment] 2016-10-05 22:29
Got it also just now

```composer create-project --prefer-dist laravel/lumen test
cd test
php artisan


  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Laravel\Lumen\Application::resourcePath()```

**Comment by GrahamCampbell** [comment] 2016-10-05 22:32
Yeh, I know. It's not been tagged yet. :)

**Comment by GrahamCampbell** [comment] 2016-10-05 22:32
Try now. We just pushed out a new release. :P

**Comment by jeroenherczeg** [comment] 2016-10-05 22:38
Super it works!

Thanks for all your great work!

**Comment by icibotaru** [comment] 2016-10-10 14:33
Guys, what changed in the release?

I get same error, i just did an update from:
`"laravel/lumen-framework": "5.2.*",`
to
`"laravel/lumen-framework": "5.3.*",`

Ty!

**Comment by martinssipenko** [comment] 2016-10-10 14:35
@icibotaru make sure that the latest illuminate version is actually installed. you can do that by inspecting `vendor/composer/installed.json`. Can you also paste the error here?

**Comment by icibotaru** [comment] 2016-10-10 14:42
All looks to be ok, 5.3 all around.
When i give: `php artisan list` i get:

```
PHP Fatal error:  Call to undefined method Laravel\Lumen\Application::resourcePath() in /var/www/tld/vendor/illuminate/support/ServiceProvider.php on line 71
[Symfony\Component\Debug\Exception\FatalErrorException]
Call to undefined method Laravel\Lumen\Application::resourcePath()
```

**Comment by martinssipenko** [comment] 2016-10-10 14:43
which 5.3 exactly? i think it was fixed in `5.3.16`

**Comment by icibotaru** [comment] 2016-10-10 14:46
Good question.
In `vendor/composer/installed.json` i have something like this:
```
"name": "laravel/lumen-framework",
"version": "dev-master",
"version_normalized": "9999999-dev",
```
Could this be the problem?

**Comment by martinssipenko** [comment] 2016-10-10 14:47
you need to lool at `illuminate/support` version

**Comment by icibotaru** [comment] 2016-10-10 14:48
```
"name": "illuminate/support",
"version": "5.3.x-dev",
"version_normalized": "5.3.9999999.9999999-dev",
```

**Comment by martinssipenko** [comment] 2016-10-10 14:55
Weird, one thing that I think you have is `minimum-stability` set to `dev`, but that should not be an issue. So composer ends up installing development version of things, instead of stable releases. 
Can you find out which commit of `laravel/lumen-framework` you have installed locally?

**Comment by icibotaru** [comment] 2016-10-10 14:59
Oh wow, look at that.
`https://api.github.com/repos/laravel/lumen-framework/zipball/e4c86170986f82423c2bbbcd69a40012ffe406a0`
This commit looks to be from september.

**Comment by martinssipenko** [comment] 2016-10-10 15:01
Perhaps some other packages you use require older version of `laravel/lumen-framework`.

Just to rule this out - you have run `composer update`, right?

**Comment by icibotaru** [comment] 2016-10-10 15:05
Yes and i have `minimum-stability` set to `dev` and i updated from 5.2 to 5.3 because of `illuminate/redis` because he wanted the 5.3 version of `illuminate/support` as strange as that sounds.

**Comment by martinssipenko** [comment] 2016-10-10 15:06
can you try removing `minimum-stability`? If you do need it for some specific packages use `@dev` for that specific package.

**Comment by icibotaru** [comment] 2016-10-10 15:08
Oh i just saw:
`https://github.com/laravel/lumen-framework/commits/master`
Stops on Sept. the 7th. and the latest commit is my version.

**Comment by martinssipenko** [comment] 2016-10-10 15:09
judging by https://github.com/laravel/lumen-framework/blob/5.3/composer.json#L63 it think, it should be installing `5.3` branch and not `master`

**Comment by icibotaru** [comment] 2016-10-10 15:15
Kinda strange,
Well removing `minimum-stability` fixed my problem and wen't to do the latest updates until commit: `c8ebc69875a2c219140b50fbb6a16c9d55d526b2`

artisan works ok now.
Thanks for the help!

**Comment by martinssipenko** [comment] 2016-10-10 15:21
Just checked packagist.org and found that `lumen-framework` `dev-master/5.3.x-dev` is pointing to `e4c86170986f82423c2bbbcd69a40012ffe406a0`.

That I believe is the cause why you were getting this. Not sure tho whether that is what's expected to be on packagist.

**Comment by icibotaru** [comment] 2016-10-10 15:29
Might be, in `vendor/composer/installed.json` related to the `laravel/lumen-framework ` json i have a `notification-url` pointing to `https://packagist.org/downloads/`
Could this be the cause?
But i can't explain how it ended being there.

**Comment by martinssipenko** [comment] 2016-10-10 15:46
Nah, thats right, just a URL that is triggered every time someone downloads `lumen-framework` using composer. Used for stats.
