### ISSUE TITLE
Helper route() don't recognize optional params

### ISSUE THREAD

**Issue by vinisouza** [laravel/lumen-framework#539] opened 2016-12-22 19:08 UTC
Hi, friends.

I'm trying to use the route() helper as the example:

**NfeController@create**
`$urlParams = ['emitterId' => $emitter->id, 'status' => 'entradas', 'key' => $nfe->chave, 'format' => 'xml'];`
`$url = route('nfe', $urlParams);`

**routes.php**
`$app->group(['prefix' => 'emitter'], function($app){`
    `$app->group(['prefix' => '{emitterId}/nfe'], function($app){`
            `$app->get('{status}/{key}[/{format}]', ['as' => 'nfe', 'uses' => 'NfeController@show']);`
    `}`
`}`

but the function returns:
http://localhost:8000/emitter/36/nfe/entradas/29161207683985000146550010000000151000000151[/xml]

The helper **route** supports optional params?

P.S.: lumen 5.3; nikic/fast-route: 1.0.1

**Comment by mstaack** [comment] 2016-12-24 08:03
Can confirm the issue

**Comment by bobbybouwmann** [comment] 2016-12-27 07:41
I don't see an optional param in your route?

**Comment by mstaack** [comment] 2016-12-28 14:18
@bobbybouwmann  what about `[/{format}]`  part? :)

**Comment by mstaack** [comment] 2016-12-29 14:06
hmm okay.. had a similiar issue.

fast route docs state:
```
    // The /{title} suffix is optional
    $r->addRoute('GET', '/articles/{id:\d+}[/{title}]', 'get_article_handler');
```

so lumen handles this differently?

**Comment by bobbybouwmann** [comment] 2016-12-29 14:47
There might be missing something in the docs... 

Anyway the routes in Lumen work the same as the routes in Laravel, so you should be fine with the documentation from Laravel: https://laravel.com/docs/5.3/routing#parameters-optional-parameters

**Comment by GrahamCampbell** [comment] 2016-12-29 14:51
> Anyway the routes in Lumen work the same as the routes in Laravel

Not quite true. The routing system in Lumen is actually entirely different from Laravel's internally. It's designed so feels the same to use though. Not everything the Laravel docs perfectly carries over.

The Lumen docs are available at: https://lumen.laravel.com/docs/5.3/routing.

**Comment by bobbybouwmann** [comment] 2016-12-29 15:44
@GrahamCampbell So there is no optional option for routes in Lumen? At least I can't find anything in the documentation about it

**Comment by GrahamCampbell** [comment] 2016-12-29 16:30
I don't know off the top of my head. You'd have to check the source code.

**Comment by mstaack** [comment] 2016-12-30 13:47
must be something around here:
https://github.com/laravel/lumen-framework/blob/5.3/src/Routing/UrlGenerator.php#L287
must be debugged sometime after new years ;)

**Comment by mstaack** [comment] 2017-01-12 12:46
whats the status here?

**Comment by mstaack** [comment] 2017-02-17 10:55
@themsaid can you have a look here?

**Comment by cristiangrama** [comment] 2017-03-04 16:59
You can use an optional route param but only at the end of the route. Lumen uses https://github.com/nikic/FastRoute so check that package out to see more about optional params.

This would work for only one optional param.
```
$app->post('/test[/{name}]', function($name = null, Request $request) {
});
```

**Comment by giovannibr** [comment] 2017-07-20 14:52
the question stays on...
you have the optional parameter:

`$app->get('/test[/{name}]', ['as' => 'test', 'uses' => 'MyController@test']);`

the issue's title saids: "Helper route()"... 
the thing is, if you try to use the helper route(), like:

`route('test')`  
`route('test', ['name' => 'myname'])`  

it supposed to return (like laravel's optional param):
"http://yourdomain.com/test"
"http://yourdomain.com/test/myname"

but it's returning:
"http://yourdomain.com/test[/{name}]"
"http://yourdomain.com/test[/myname]"

**Comment by nepster-web** [comment] 2018-07-29 14:55
I have a similar problem. But the above decision seems to me doubtful.
Are there any progress in this problem?

**Comment by driesvints** [comment] 2018-10-02 09:37
I can confirm that this is a bug and can reproduce it. Open for PR's to fix this.

**Comment by JacksonIV** [comment] 2018-10-02 09:44
@driesvints Do you think this could be solved in the regex in the route method in UrlGenerator.php?

**Comment by driesvints** [comment] 2018-10-02 09:45
@JacksonIV saw your PR and yeah I believe so. Just need to figure out the regex I suppose 😅

**Comment by JacksonIV** [comment] 2018-10-02 09:47
@driesvints Yeah, i closed the PR myself because the tests failed.

**Comment by JacksonIV** [comment] 2018-10-23 19:12
@driesvints I tried a few things, but i don't know how to solve this neatly. Have you got any thoughts on this?

**Comment by yuloh** [comment] 2018-10-24 18:02
@JacksonIV I have this working in a branch but the pull request was closed (#828).  Not sure what alternative solution would be preferred.

**Comment by JacksonIV** [comment] 2018-10-27 11:40
This should be fixed in the next release.

**Comment by GrahamCampbell** [comment] 2018-10-27 11:53
🚀

**Closed by GrahamCampbell** 2018-10-27 11:53 UTC
Labels: action needed
