### ISSUE TITLE
Undefined namespaces in file: RoutesRequests

### ISSUE THREAD

**Issue by pedroskakum** [laravel/lumen-framework#643] opened 2017-08-12 19:55 UTC
- Lumen Version: 5.4.*
- PHP Version: 7.0
- Database Driver & Version: pgsql 9.4

### Description:
In the namespace `Laravel\Lumen\Concerns\RoutesRequests`,  there are two statements not found, does anyone know why?

`use Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory;
use Psr\Http\Message\ResponseInterface as PsrResponseInterface;`

### Steps To Reproduce:

watch: https://youtu.be/gGLOt99K1fU

**Comment by yuloh** [comment] 2017-08-14 15:50
Those are only used for [PSR-7](https://lumen.laravel.com/docs/5.4/requests#psr7-requests) support.  It's an optional dependency that is only used if you ask for those classes from the container.

Duplicate of #509.

**Closed** 2017-09-05 16:09 UTC
