### ISSUE TITLE
'ReflectionException' with message 'Class path.storage does not exist'

### ISSUE THREAD

**Issue by ant-ia** [laravel/lumen-framework#504] opened 2016-10-12 09:07 UTC
after run:
`php artisan`

get this errors:
`PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class path.storage does not exist' in /Applications/MAMP/htdocs/folder-project/vendor/laravel/framework/src/Illuminate/Container/Container.php:748
Stack trace:`

`PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Uncaught exception 'ReflectionException' with message 'Class path.storage does not exist' 
in /Applications/MAMP/htdocs/folder-project/vendor/laravel/framework/src/Illuminate/Container/Container.php:748
Stack trace:`

**Comment by GrahamCampbell** [comment] 2016-10-12 13:01
Looks like a bug in a package you're using perhapse?

**Comment by ant-ia** [comment] 2016-10-12 13:05
No I do not think depend on some package, because it stopped working suddenly

this is composer.json

`{
    "name": "laravel/lumen",
    "description": "The Laravel Lumen Framework.",
    "keywords": ["framework", "laravel", "lumen"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/lumen-framework": "5.3.*",
        "vlucas/phpdotenv": "~2.2",
        "wn/lumen-generators": "^1.1"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "phpunit/phpunit": "~5.0",
        "mockery/mockery": "~0.9",
        "asamaru7/eloquent-model-generator-for-lumen": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/",
            "database/"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ]
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
`

**Comment by bobbybouwmann** [comment] 2016-10-12 13:22
What is the exact version of Lumen that you use?

**Comment by ant-ia** [comment] 2016-10-12 13:24
5.3.1 updated today, but already with 5.3 had problems with php artisan

**Comment by GrahamCampbell** [comment] 2016-10-12 16:09
Looks like it's due to asamaru7/eloquent-model-generator-for-lumen.

**Comment by ant-ia** [comment] 2016-10-12 16:24
No I do not think so.
I deleted that package but the error persists

**Comment by bthibault** [comment] 2016-11-11 13:49
I'm running into similar weird problems
1. storage exceptions occasionaly and this message intermittenlty 

I think its related

2016-11-11 08:34:12] lumen.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\Request does not exist' in /var/www/html/dbapi/api/vendor/illuminate/container/Container.php:573
Stack trace:
#0 /var/www/html/dbapi/api/vendor/illuminate/container/Container.php(573): ReflectionParameter->getClass()
#1 /var/www/html/dbapi/api/vendor/illuminate/container/Container.php(534): Illuminate\Container\Container->addDependencyForCallParameter(Object(ReflectionParameter), Array, Array)
#2 /var/www/html/dbapi/api/vendor/illuminate/container/Container.php(506): Illuminate\Container\Container->getMethodDependencies(Array, Array)
#3 /var/www/html/dbapi/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(610): Illuminate\Container\Container->call(Array, Array)
#4 /var/www/html/dbapi/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(577): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#5 /var/www/html/dbapi/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(550): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\GuideController), 'show', Array)
#6 /var/www/html/dbapi/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(512): Laravel\Lumen\Application->callControllerAction(Array)
#7 /var/www/html/dbapi/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(497): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#8 /var/www/html/dbapi/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(467): Laravel\Lumen\Application->handleFoundRoute(Array)
#9 /var/www/html/dbapi/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(399): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#10 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#11 /var/www/html/dbapi/api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /var/www/html/dbapi/api/vendor/palanik/lumen-cors/LumenCors.php(105): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/html/dbapi/api/vendor/illuminate/pipeline/Pipeline.php(137): palanik\lumen\Middleware\LumenCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/html/dbapi/api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /var/www/html/dbapi/api/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/html/dbapi/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(647): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 /var/www/html/dbapi/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(400): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#19 /var/www/html/dbapi/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(341): Laravel\Lumen\Application->dispatch(NULL)

**Comment by hpaknia** [comment] 2016-12-28 01:38
In my case got fixed by adding following lines right after defining $app in bootstrap/app.php file:
```php
$app = new Laravel\Lumen\Application(
        realpath(__DIR__ . '/../')
);

$app->instance('path.config', app()->basePath() . DIRECTORY_SEPARATOR . 'config');
$app->instance('path.storage', app()->basePath() . DIRECTORY_SEPARATOR . 'storage');

//$app->withFacades();
$app->withEloquent();
```

**Comment by lsl** [comment] 2017-03-12 10:46
This is happening because Illuminate's helpers are being loaded before Lumen's.

My autoload_files.php:

```
'f0906e6318348a765ffb6eb24e0d0938' => $vendorDir . '/laravel/framework/src/Illuminate/Foundation/helpers.php',
'bee9632da3ca00a99623b9c35d0c4f8b' => $vendorDir . '/laravel/lumen-framework/src/helpers.php',
```

This happens when laravel/framework gets required by something, composer wipes out lumens vendor/illuminate file with vendor/laravel/framework (laravel/framework composer.json says replace illuminate.)

What's weirder is it seems like we're beholden to composer and how it scores/sorts autoload_files.php. I managed to get this to load in different (working) orders but I'm not 100% sure how - and frankly don't have time for this. But that does confirm @bthibault's issue.

This issue also persists after removing offending packages from composer.json and running composer update. I suspect this is a caching problem with the laravel replace and composer. 

These steps seem to fix the issue, at least intermittently: (and may help reproducing the issue!)

1. Deleting your composer cache (```rm -rf ~/.composer/cache/laravel/framework```), 
2. Delete your composer.lock file (not 100% this is required)
3. Delete your vendor dir (don't worry it mostly gets reloaded from cache)
4. Run ```composer update```

**Comment by stevethomas** [comment] 2017-07-07 06:34
In my case I was running `phpunit` from my $PATH (~/.composer/bin) rather than the project vendor/bin/phpunit file, and I guess for reasons mentioned by @lsl, laravel overloaded lumen helpers.

This only seems to have emerged after I recently added config/filesystems.php. 

The solution was to run tests with `vendor/bin/phpunit` instead.

>PHP Fatal error:  Uncaught ReflectionException: Class path.storage does not exist in /Users/stevethomas/Code/Lp/lp-api/vendor/illuminate/container/Container.php:729
>Stack trace:
>#0 /Users/stevethomas/Code/Lp/lp-api/vendor/illuminate/container/Container.php(729): ReflectionClass->__construct('path.storage')
>#1 /Users/stevethomas/Code/Lp/lp-api/vendor/illuminate/container/Container.php(608): Illuminate\Container\Container->build('path.storage')
>#2 /Users/stevethomas/Code/Lp/lp-api/vendor/illuminate/container/Container.php(575): Illuminate\Container\Container->resolve('path.storage')
>#3 /Users/stevethomas/Code/Lp/lp-api/vendor/laravel/lumen-framework/src/Application.php(208): Illuminate\Container\Container->make('path.storage')
>#4 /Users/stevethomas/.composer/vendor/illuminate/support/Illuminate/Support/helpers.php(33): Laravel\Lumen\Application->make('path.storage')
>#5 /Users/stevethomas/.composer/vendor/illuminate/support/Illuminate/Support/helpers.php(790): app('path.storage')
>#6 /Users/stevethomas/Code/Lp/lp-api/config/filesy in /Users/stevethomas/Code/Lp/lp-api/vendor/illuminate/container/Container.php on line 729

**Comment by achton** [comment] 2017-08-24 08:12
Consider where `storage_path()` is being called from. In my case, it was called from the app's config file, which was too soon. Moving the call into the app proper fixed this issue for me.

**Comment by gurpalsingh1919** [comment] 2018-07-12 13:18
Same issue reported in laravel 5.4

**Comment by driesvints** [comment] 2018-10-02 10:18
Please check https://github.com/laravel/lumen-framework/issues/798 and see if the problem still exists in 5.7. Otherwise feel free to ping me to reopen :)

**Closed by driesvints** 2018-10-02 10:18 UTC

**Comment by geodeveloper** [comment] 2018-11-21 16:18
This issue still exists in 5.7

If you are running lumen and if any required package uses as a dependency `illuminate/framework` it will fail.

**Comment by defaye** [comment] 2019-06-06 08:43
In my case I foolishly didn't twig that I needed to call the `parent::tearDown()` after my own code - the inverse of `setUp()`, of course.

```
    public function tearDown(): void
    {
        //////////////////////////////
        // Your code should go here //
        //////////////////////////////
        parent::tearDown();
    }
```

**Comment by judgej** [comment] 2019-07-04 09:35
Lumen 5.8 also - I just hit this problem.

**Comment by HenkPoley** [comment] 2019-07-31 09:41
After `composer require --dev nunomaduro/larastan` you bump into this as well. Which purports to be Lumen compatible: https://github.com/nunomaduro/larastan

It appears it causes `illuminate/container` to be removed (among others).

If you don't particularly need Larastan, you can recover from this with removing `nunomaduro/larastan` from your `composer.json` and running `rm -rf vendor composer.lock && composer install`. With a remaining composer.lock it seems to linger with a removed  `illuminate/container` even after removing `nunomaduro/larastan` from your `composer.json`

**Comment by kundancool** [comment] 2019-11-12 07:28
Clearing composer cache and install vendor packages fixed in my case.
```
composer clear-cache
composer install
```

**Comment by ian-nisbet** [comment] 2020-01-15 09:57
Try this: 

$app->instance('path.config', app()->getConfigurationPath());
$app->instance('path.storage', app()->storagePath());

**Comment by william-mymy** [comment] 2020-10-05 14:40
Hi, I encountered the same problem yesterday. I did some research and end up here. Although this issue didn't help me, I was able to figure out that it was one of the packages which were incompatible with my Lumen app. Later, I figured out that it happened because of the latest version (8.x) of `DarkaOnLine/SwaggerLume` which I installed together with Lumen version 7.x. 

To solve the problem I just removed the latest version of SwaggerLume and installed 7.x as specified in the documentation. Hope this will help people with similar error. Thanks. :)

**Comment by Jiannei** [comment] 2021-03-12 02:27
Yeah, I also encountered the same problem now. 

Lumen 8.x ,there are two `storage_path` helper functions shown below.

![image](https://user-images.githubusercontent.com/46595807/110879766-7debef00-8318-11eb-8399-f0f9efd704ab.png)

![image](https://user-images.githubusercontent.com/46595807/110879894-b8558c00-8318-11eb-9408-5e35e4f600a3.png)

![image](https://user-images.githubusercontent.com/46595807/110879951-d0c5a680-8318-11eb-9829-b2f49ed5484e.png)

I used `composer why laravel/framework`, found `appstract/laravel-opcache`，removed it or  set `path.storage` in `bootstrap\app.php`  =>  https://github.com/laravel/lumen-framework/issues/504#issuecomment-269410657

![image](https://user-images.githubusercontent.com/46595807/110880545-c48e1900-8319-11eb-95a1-c933a3d20044.png)

**Comment by timersys** [comment] 2021-03-27 14:21
Same issue in lumen 8.x after doing  php artisan vapor-ui:install

**Comment by ClCfe** [comment] 2021-04-27 17:58
> Try this:
> 
> $app->instance('path.config', app()->getConfigurationPath());
> $app->instance('path.storage', app()->storagePath());

I think for config_path, you should use
`$app->instance('path.config', app()->configPath());`
that s what theyr do in laravel8 or lumen8

**Comment by ClCfe** [comment] 2021-04-27 18:01
> Yeah, I also encountered the same problem now.
> 
> Lumen 8.x ,there are two `storage_path` helper functions shown below.
> 
> ![image](https://user-images.githubusercontent.com/46595807/110879766-7debef00-8318-11eb-8399-f0f9efd704ab.png)
> 
> ![image](https://user-images.githubusercontent.com/46595807/110879894-b8558c00-8318-11eb-9408-5e35e4f600a3.png)
> 
> ![image](https://user-images.githubusercontent.com/46595807/110879951-d0c5a680-8318-11eb-9829-b2f49ed5484e.png)
> 
> I used `composer why laravel/framework`, found `appstract/laravel-opcache`，removed it `compsoer remove appstract/laravel-opcache` (rm -rf vendor/ & composer install) or set `path.storage` in `bootstrap\app.php` => [#504 (comment)](https://github.com/laravel/lumen-framework/issues/504#issuecomment-269410657)
> 
> ![image](https://user-images.githubusercontent.com/46595807/110880545-c48e1900-8319-11eb-95a1-c933a3d20044.png)

I think you found the bug, the definition of storage_path() is wrong in laravel8 helpers.php

looking at config_path(), you can see it is exactly the same definition in lumen and laravel, so no conflict

**Comment by Carsak** [comment] 2021-11-25 09:51
Same issue with Lumen 8^ version

I installed "darkaonline/l5-swagger": "^8.0" and after run command 
`php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider`
But got error

`Fatal error: Uncaught ReflectionException: Class path.storage does not exist in C:\MyProjects\jpost-api\vendor\laravel\framework\src\Illuminate\Container\Container.php:873`

Running 
```
composer clear-cache
composer install
```
didnt help

**Comment by Carsak** [comment] 2021-11-25 10:06
Swagger laravel has separate version for lumen
https://github.com/DarkaOnLine/SwaggerLume

So I downloaded this version and all fine now
