### ISSUE TITLE
$this->authorize() Always breaks with Create and View Policies: returns 403

### ISSUE THREAD

**Issue by ashjames** [laravel/lumen-framework#926] opened 2019-05-31 21:45 UTC
- Lumen Version: 5.8.8
- PHP Version: 7.3.4
- Database Driver & Version: MySQL 15.1 Distrib 10.1.38-MariaDB

![error](https://user-images.githubusercontent.com/12672046/58734197-a4b08e00-83ee-11e9-99e5-a7bd8b3aa313.JPG)

### Description:

When using $this->authorize(xxx) with either create or view, error 403 always gets returned. Update and delete policies both work fine.

### Steps To Reproduce:

1. `lumen new blog`
1. Installed package `composer require flipbox/lumen-generator --dev` to add more functionality to artisan.
    * In the file `boostrap/app.php` register the installed package:  `$app->register(Flipbox\LumenGenerator\LumenGeneratorServiceProvider::class);`
1. Rename `.env.example` to `.env` and in the file change `APP_DEBUG` to **true**.
1. In the following steps I will focus on reproducing the issue with `POST` route `match/new`.

#### Routes
``` php
$router->group([
    'prefix' => 'match'
], function ($router) {
    $router->get('/', 'MatchController@index');
    $router->post('/new', 'MatchController@store');
});
```

#### Model
``` php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Match extends Model
{
    // protected $guarded = [];
}
```
#### Controller
``` php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Match;

class MatchController extends Controller
{
    public function store(Request $request)
    {
        error_log('>> MatchController [store]'); // accessed

        // Few methods attempted, all return 403 Forbidden
        $this->authorize('create');
        // $this->authorize('create', $request->user());
        // $this->authorize('create', Match::class);
        // $this->authorize('create', \App\Match::class);

        return response()->json('response');
    }

    public function index(Request $request)
    {
        return response()->json('index');
    }
}
```

#### Policy
``` php
<?php

namespace App\Policies;

use App\User;
use App\Match;
use Illuminate\Auth\Access\HandlesAuthorization;

class MatchPolicy
{
    use HandlesAuthorization;

    /**
     * Determine whether the user can view the match.
     *
     * @param  App\User  $user
     * @param  App\Match  $match
     * @return mixed
     */
    public function view(User $user, Match $match)
    {
        // Policy never gets accessed.
        error_log('MatchPolicy [view]');
        return true;
    }

    /**
     * Determine whether the user can create matches.
     *
     * @param  App\User  $user
     * @return mixed
     */
    public function create(User $user)
    {
        // Policy never gets accessed. 
        error_log('MatchPolicy [create]');
        return true;
    }
}
```

#### AuthServiceProvider.php

Register the policy in `AuthServiceProvider.php`.

``` php
...

public function boot()
{
	Gate::policy('App\Match', 'App\Policies\MatchPolicy');
	...
}
```

**Comment by driesvints** [comment] 2019-06-04 13:16
You don't seem to be passing a resource in `$this->authorize('create');`. Try `$this->authorize('create', Match::class);`?

**Comment by ashjames** [comment] 2019-06-04 13:29
> 
> 
> You don't seem to be passing a resource in `$this->authorize('create');`. Try `$this->authorize('create', Match::class);`?

Please refer to Controller heading, all of these and more return 403.

```php
// Few methods attempted, all return 403 Forbidden
// $this->authorize('create');
// $this->authorize('create', $request->user());
// $this->authorize('create', Match::class);
// $this->authorize('create', \App\Match::class);
```

**Comment by driesvints** [comment] 2019-06-04 15:20
Ah sorry, missed that. I can reproduce this but am clueless at what's going on. Everything seems to be set up properly but I'm still getting the forbidden error.

**Comment by Kieran-Brown** [comment] 2019-09-08 11:28
A bit late to the party, in the examples given there doesn't seem to be an indication of authentication? The user just needs marking as nullable in the policy, I think that is the problem here?

```php
<?php

namespace App\Policies;

use App\User;
use App\Match;
use Illuminate\Auth\Access\HandlesAuthorization;

class MatchPolicy
{
    use HandlesAuthorization;

    /**
     * Determine whether the user can view the match.
     *
     * @param  \App\User  $user
     * @param  \App\Match  $match
     * @return mixed
     */
    public function view(?User $user, Match $match)
    {
        return true;
    }

    /**
     * Determine whether the user can create matches.
     *
     * @param  \App\User  $user
     * @return mixed
     */
    public function create(?User $user)
    {
        return true;
    }
}
```

**Comment by driesvints** [comment] 2019-09-09 11:32
@ashjames can you try that?

**Comment by driesvints** [comment] 2020-01-30 11:01
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Closed by driesvints** 2020-01-30 11:01 UTC
Labels: bug

**Comment by stevebaros** [comment] 2020-06-12 11:57
Still experiencing the same issue
