### ISSUE TITLE
Presence verifier has not been set exception on validator rule exists

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/lumen-framework#584] opened 2017-03-06 14:39 UTC
I am creating a manual validator like this:

```php
$validator = Validator::make(['productNumber' => $productNumber], [
    'productNumber' => 'exists:products,product_number',
]);
```

The entry exists in the database, but I am getting the following error:

```
RuntimeException in Validator.php line 954:
Presence verifier has not been set.

in Validator.php line 954
at Validator->getPresenceVerifier() in Validator.php line 970
at Validator->getPresenceVerifierFor(null) in ValidatesAttributes.php line 559
at Validator->getExistCount(null, 'product', 'product_number', '9789510384725', array('product', 'product_number')) in ValidatesAttributes.php line 542
at Validator->validateExists('productNumber', '9789510384725', array('product', 'product_number'), object(Validator)) in Validator.php line 338
at Validator->validateAttribute('productNumber', 'Exists') in Validator.php line 253
```

**Comment by yuloh** [comment] 2017-03-08 21:30
It's [only set if it was registered manually or you enabled eloquent](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Validation/ValidationServiceProvider.php#L41).

Did you uncomment `$app->withEloquent()`?

Alternatively you can register your own presence verifier as `validation.presence` in the container.

**Comment by lasselehtinen** [comment] 2017-03-09 09:48
I have not enabled Eloquent, since I have no use for it in this particular project. I guess I could enable it even though I might get a small performance hit.

I am not too familiar with validation internals in Laravel/Lumen. I was just wondering why this validation rule requires Eloquent anyway? The ruleseems to be using the query builder syntax so I guess it is coming from somewhere else.

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Validation/Rules/Exists.php

**Comment by yuloh** [comment] 2017-03-09 14:15
the `$app->withEloquent()` method actually enables the query builder too.  It's registering the [DatabaseServiceProvider](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/DatabaseServiceProvider.php), which is required to use the query builder.

**Comment by lasselehtinen** [comment] 2017-03-09 14:26
Hmm, you are completely sure? Because the app I am building has `$app->withFacades()` enabled but not  `$app->withEloquent();` and the query builder works just fine.

**Comment by yuloh** [comment] 2017-03-09 14:41
I guess If you resolve the query builder later it will work because `Application::make` checks that it has a binding and lazily registers the database service provider.

The problem is the validation service provider checks if the database service provider is already bound and skips registering the presence verifier if it's not.  

So it's not going to register the presence verifier unless you make the database component at least once before using the validator.

**Comment by lasselehtinen** [comment] 2017-03-09 15:03
Thanks for the the explanation but it goes way over my expertise :) Is this considered a bug or not? For me it does not make sense to require Eloquent for a certain validation rule, even though it is database related.

**Comment by aacsssh** [comment] 2017-05-11 09:55
I had the same issue for my custom validator class in Laravel 5.4. After doing some googling, I kinda fixed it ('RuntimeException: Presence verifier has not been set.' is not bugging me anymore ) by calling 'setPresenceVerifier' method in the constructor of my custom validator class. 

        function  __construct(Validator $validator)
	    {
		$this->validator = $validator;
		$this->validator->setPresenceVerifier(app('validation.presence'));
	    }

Unless I find any other way to fix this, I am sticking with it. Hope this may help. Thank you.

**Comment by jefersonralmeida** [comment] 2018-01-11 23:41
It's pretty old, but I got the same problem, and found a solution. To me it's a bug on Laravel, I'm trying to find a good way to fix it and open a PR to Laravel, but it's another matter.
There is a simple workaround:
You just need to call `app('db')` or the DB facade (if you use facades, I don't like them), before creating the validator. In my case, I just included on my app.php:
```
//$app->withFacades();

// enabled just to set presence verifier
//$app->withEloquent();
app('db');
```

**Comment by yuloh** [comment] 2018-01-12 18:18
Calling `app('db') is essentially the same thing as enabling `$app->withEloquent()`:

https://github.com/laravel/lumen-framework/blob/a72270565651e526a3162b7b7767298a31514b81/src/Application.php#L698

It isn't really a bug.  If you have not enabled the database component Lumen can't use it for the presence verifier.  You can verify that is the case by looking at the line of code I linked previously:

https://github.com/laravel/framework/blob/8a74cf931b9df281707cef973ee9fba5b18793e8/src/Illuminate/Validation/ValidationServiceProvider.php#L41

The other workaround is also doing the same thing.  Resolving `validation.presence` forces `db` to resolve.

If Laravel didn't check for the `db` binding before registering the presence verifier it would force everyone to load the database component, even if they weren't using it.

The docs should probably be updated to state that the `exists` and `unique` rules require uncommenting `$app->withEloquent()`.

**Comment by driesvints** [comment] 2018-10-01 15:28
You'll indeed need to uncomment the `$app->withEloquent()` rule. Feel free to make a PR against the docs if you think that'll be more clear 👍

**Closed by driesvints** 2018-10-01 15:28 UTC

**Comment by esinanturan** [comment] 2020-10-13 15:16
I am having same issue with lumen 8 and `$app->withEloquent()` enabled any any of the suggestions up did not help but validation works if I use `$this->validate($request,['email'=>'unique:users'])` but it gives error if I try it by dependency injecting `use Illuminate\Validation\Factory` is there a bug about it ?
