### ISSUE TITLE
Illuminate\Http\Request::fingerprint method does not work in Lumen; Request->route() non-object

### ISSUE THREAD

**Issue by k98kurz** [laravel/lumen-framework#348] opened 2016-02-02 19:26 UTC
No matter what I do, I cannot get the [fingerprint](https://laravel.com/api/5.2/Illuminate/Http/Request.html#method_fingerprint) method to work, and it is because of an issue with the way the fingerprint method gets its values.
### The error

```
FatalErrorException in Request.php line 821:
Call to a member function methods() on a non-object
    1. in Request.php line 821
    2. at Application->handleShutdown() in RegistersExceptionHandlers.php line 55
    3. at Application->Laravel\Lumen\Concerns\{closure}()
```
### The offending code

```
    public function fingerprint()
    {
        if (! $this->route()) {
            throw new RuntimeException('Unable to generate fingerprint. Route unavailable.');
        }

        return sha1(
            implode('|', $this->route()->methods()).
            '|'.$this->route()->domain().
            '|'.$this->route()->uri().
            '|'.$this->ip()
        );
    }
```

The specific line is `implode('|', $this->route()->methods()).`.

**Comment by k98kurz** [comment] 2016-02-02 20:19
I have added this to my `bootstrap/app.php` file as a temporary fix.

    // fix Illuminate\Http\Request
    function fingerprint()
    {
        $r = request();
        return hash('sha1', json_encode([
            $r->url(),
            $r->method(),
            $r->ips(),
            $r->header(),
            $r->all()
        ]));
    }

**Comment by MateuszKoguc** [comment] 2016-05-16 16:13
@k98kurz I would consider putting `header()` and `all()` inside. Attacker can easily omitt throttling putting only dummy GET parameter into URL:
`example.com/api/endpoint?dummy=123`
`example.com/api/endpoint?dummy=124`
Those two hits will generate different SHA1, so can't match to each other...

`Illuminate\Http\Request` is extended from `Symfony\Component\HttpFoundation\Request`; my fix is using those methods to get the same informations as in original code:

```
return sha1(
    $request->getMethod() .
    '|' . $request->getHost() .
    '|' . $request->getPathInfo() .
    '|' . $request->getClientIp()
);
```

Implode was skipped as in laravel router ->methods() is returning array of `[`POST`,'GET'....]` when you use `Route::any(...)`. In lumen `nikic/fast-route`router was implemented, which require specific http method for each route.

**Comment by k98kurz** [comment] 2016-05-24 14:53
My goal was simply to allow an easy way to cache things on a per-request basis rather than to throttle connections. I'll see about removing dummy `GET` params in the url when I get a chance, though.

**Comment by driesvints** [comment] 2018-10-02 12:29
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by jsamr** [comment] 2018-10-06 14:54
@driesvints I just stumbled on this one today, lumen v5.7.1.

**Comment by yuloh** [comment] 2018-10-17 15:38
I can confirm this still does not work.  It won't work until `Request::route` returns an object with a `methods` method.  My [proposal to fix that](https://github.com/laravel/ideas/issues/71) was rejected.  The proposal that [was merged](https://github.com/laravel/lumen-framework/pull/803) only fixes part of the problem.

**Comment by driesvints** [comment] 2018-10-18 08:01
Hey guys. Thanks for reporting. Re-opening this. I'll try to have a look at a later time. Feel free to send in a PR which can fully fix this. Try to add a failing test case if possible.

**Comment by yuloh** [comment] 2018-10-18 14:42
Hi Dries,

As I said above, I originally attempted to fix this in 2016 and my proposal was closed without offering any alternative solutions.  I would love to fix this but I have no idea how the maintainers would like this to be fixed.

Since #803 was merged it seems like the preferred approach is to subclass `Illuminate\Http\Request` instead?  Should we make a Lumen Route object then that has all the methods the Request class expects?

**Comment by JacksonIV** [comment] 2018-10-19 20:46
I've opened a PR which should make the fingerprint method compatible with Lumen.

**Comment by driesvints** [comment] 2018-10-21 14:31
Thanks @JacksonIV!

**Closed by driesvints** 2018-10-21 14:31 UTC
Labels: action needed
