### ISSUE TITLE
Generating URLs for named routes on commands is missing hostname and port

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/lumen-framework#513] opened 2016-10-31 16:24 UTC
Hi,

Seems like the route helper is not working properly on commands. I would like to generate a URL to a named route with parameters but it seems to be always missing the hostname and port. It works fine on controllers and route closures but not on commands.

routes.php which returns http://localhost:12345/user/1
```
<?php
$app->get('user/{id}', ['as' => 'user', function ($id) {
    return route('user', ['id' => 1]);
}]);
```

Same route helper on the command:

```
/**
 * Execute the console command.
 *
 * @return mixed
 */
public function handle()
{
    $url = route('user', ['id' => 1]);
    $this->info($url);
}
```

```
vagrant@homestead:~/Code/lumen_route_helper$ php artisan test:url
http://:/user/1
```

**Comment by molteber** [comment] 2016-11-08 21:40
As a temporary solution to this problem, i added this to my console kernel file:
```php
    protected function prepareConsoleUrl()
    {
        $url = env('APP_URL', 'http://localhost');
        $urlParts = parse_url($url);

        if (isset($urlParts['path']) && mb_strlen($urlParts['path']) > 1) {
            $_SERVER['SCRIPT_NAME'] = $urlParts['path'].DIRECTORY_SEPARATOR.'index.php';
            $_SERVER['SCRIPT_FILENAME'] = getenv('PWD').DIRECTORY_SEPARATOR.$urlParts['path'].DIRECTORY_SEPARATOR.'index.php';
        }
        $this->app->instance('request', Request::create($url, 'GET', [], [], [], $_SERVER));
    }
```
and to the constructor i added `$this->prepareConsoleUrl();`

I fetched the code from this commit: https://github.com/j3j5/framework/commit/920f023e1bd11de1a6a2a0e923a0cce7481110d9

That should do it until a real solution is added to lumen

**Comment by FractalizeR** [comment] 2017-05-24 13:55
I have the same problem and it's still not fixed.

**Comment by GrahamCampbell** [comment] 2017-05-24 14:12
We're open to PRs to fix it.

**Comment by solofeed** [comment] 2017-10-24 15:35
Up. The issue still exists.

**Comment by aivanovbelkacar** [comment] 2017-11-01 12:34
Still exists

**Comment by matthewerskine** [comment] 2017-11-04 22:36
Still getting this problem anywhere outside of immediate routes, for some reason the Symfony base request class isn't configured the same way it is with Laravel. In Laravel, it uses the 'HOST' header to determine the host for the root URL. This seems to be missing in Lumen... 

Line: 1258 in vendor/symfony/http-foundation/Request.php
```php
public function getHost()
{
    // Laravel: 'foo.bar'
    // Lumen: ''
    dd($this->headers->get('HOST'));
}
```

I'll keep digging

**Comment by solofeed** [comment] 2017-11-20 17:36
@matthewerskine @lasselehtinen 
Here resolved the problem
https://laravel-news.com/using-named-routes-lumen-test

**Comment by urukalo** [comment] 2018-01-31 14:38
@solofeed this is ugly solution, and didnt work with custom headers

is there any way to route() helper return url with path and port without disturbing request and headers

**Comment by solofeed** [comment] 2018-01-31 14:47
@urukalo It is not my solution)
If you have better solution, tell us please)

**Comment by solofeed** [comment] 2018-01-31 14:49
For me, the previous solution did not work.
So I had to write temporary overhead 
`// TODO: Remove after fix https://github.com/laravel/lumen-framework/issues/513
        $uri = str_replace('http://:', 'http://localhost', $uri);`

**Comment by urukalo** [comment] 2018-02-05 16:21
@solofeed 
i have similar temp fix
in TestCase i override call method with:
` 
public function call($method, $uri, $parameters = [], $cookies = [], $files = [], $server = [], $content = null)
    {
        $uri = str_replace('http://:', '', $uri);
        parent::call($method, $uri, $parameters, $cookies, $files, $server, $content);
    }
`

now waiting for fix .. anyone have idea how to resolve this problem?

**Comment by dvdmarchetti** [comment] 2018-03-07 17:38
This should work:
```php
// Assuming $app is an instance of \Laravel\Lumen\Application
$app->make('url')->forceRootUrl(env('APP_URL', 'http://localhost/'));
```

You can enable the AppServiceProvider and put into register method to force the root url in testing evironment or eventually edit the createApplication method in TestCase.php like this (do not forget to provide a proper APP_URL in .env config):

```php
public function createApplication()
{
    $app = require __DIR__.'/../bootstrap/app.php';

    $app->make('url')->forceRootUrl(env('APP_URL', 'http://localhost/'));

    return $app;
}
```

**Comment by gazben** [comment] 2018-03-11 20:13
@dvdmarchetti @lasselehtinen  I think I found the issue and submitted the fix. Can you guys test it please? Does it fix your problem?

**Comment by solofeed** [comment] 2018-03-15 10:00
Does not fix the problem

**Comment by dvdmarchetti** [comment] 2018-03-15 10:20
@solofeed @urukalo Have you tried my solution as well?

**Comment by solofeed** [comment] 2018-03-15 12:09
@dvdmarchetti Yes, your solution works well) thanks

**Comment by driesvints** [comment] 2018-10-02 13:13
Going to re-open this because it still seems to be a problem.

**Comment by mstaack** [comment] 2018-10-02 14:17
there is also: https://github.com/vluzrmos/lumen-url-host

**Comment by JacksonIV** [comment] 2018-10-03 05:50
@driesvints I’m currently unable to test, but isn’t this issue related to PR #805? In that case it might already be fixed.

**Comment by driesvints** [comment] 2018-10-04 07:45
@JacksonIV I was still able to reproduce this. I think the problem is that it happens when running `phpunit`.

**Comment by JacksonIV** [comment] 2018-10-08 21:13
@driesvints The route helper works in regular commands and queues in my tests. However, it doesn't work in Phpunit because the kernel is never bootstrapped when running tests. If you call this:

`app('Illuminate\Contracts\Console\Kernel');`

right before you call the route helper in your test, it'll work.

I'm not sure how you'd want to see this fixed, because it can be done in multiple ways. The kernel has to be bootstrapped somewhere within the instantiation of the tests.

**Comment by driesvints** [comment] 2018-10-09 08:08
Yeah, just like here: https://github.com/laravel/lumen/blob/master/bootstrap/app.php#L46-L49

We'll need a base test class which bootstraps the app with this binding before it'll properly work. This is probably something for a new major release. I'll ask some input from @taylorotwell on this.

**Comment by JacksonIV** [comment] 2018-10-19 23:31
@driesvints I took a closer look at this and it seems Lumen will already boot when running tests. However, since the application will boot through the console, it won't have a base url. This issue was fixed in the console kernel for regular commands.

When you run tests in Lumen it will not try to boot Lumen as a console application but as a regular application instead, that's why the fix doesn't work. 

I've made a PR where i set the root url of the url generator to the `APP_KEY` environment value when Lumen boots in the testing environment.

**Comment by driesvints** [comment] 2018-10-21 14:38
Sweet. Thanks man!

**Closed by driesvints** 2018-10-21 14:38 UTC
Labels: action needed, needs review

**Comment by MatinRh** [comment] 2020-03-23 14:14
This problem still exists! anyone going to fix it?

**Comment by ant100** [comment] 2020-08-11 21:53
This problem still happens
